config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :posts, only: [:new, :create, :index]
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title,  presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  has_many  :posts
  
  validates :name,  presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, length: { minimum: 6 }

  # Возвращает случайный токен
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Возвращает хешированный токен
  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    
    # Создаёт хешированный remember token экземпляру User
    def create_remember_token
      self.remember_digest = User.digest(User.new_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = 'Post created'
      redirect_to root_path
    else
      flash.now[:error] = 'Something wrong'
      render 'new', status: 422
    end
  end



  private

    def post_params
      params.require(:post).permit(:title, :body)  
    end

    # before filter/action
    def signed_in_user
      unless signed_in?
        redirect_to signin_url
      end
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      flash[:success] = 'Thank you for signing in!'
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new', status: 422
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_digest, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_digest: remember_token)
  end



  def sign_out
    current_user.update_attribute(:remember_digest,
                                User.digest(User.new_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<div>
  <% if signed_in? %>
  <%= link_to "#{current_user.name} Sign out", signout_path, data: { "turbo-method": :delete } %>
  <% else %>
    <%= link_to 'Sign in', signin_path %>
  <% end %>
</div>

<h1>Members Only Posts</h1>

<% @posts.each do |post| %>
  <% if signed_in? %>
    <p>
      Posted by:
      <%= post.user.name %>
    </p>
  <% end %>
  <h4><%= post.title %></h4>  
  <p><%= post.body %></p>
<% end %>

<% if signed_in? %>
  <%= link_to "Create a Post", new_post_path %>
<% end %>

app/views/posts/new.html.erb
<%= form_for(:post, url: posts_path) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/>
  <%= f.label :body%>
  <%= f.text_area :body %>

  <%= f.submit "Create" %>
<% end %>
  